# WebLinkCollector example configuration (YAML format)

initialUrl: https://example.com
depth: 2
delayMs: 2000
logLevel: info
format: json

# CSS selector to limit link extraction on the initial page
selector: .main-content a

# Filters define which URLs will be collected
filters:
  # First filter condition (OR logic between filter objects)
  - domain: example.com
    pathPrefix: /blog
  
  # Second filter condition
  - domain: api.example.com